### ISSUE TITLE
.sum-time, .req-time, .parse-timeのafterを"ms"にする

### ISSUE THREAD

**Issue by Yukinyaaa** [Yukinyaaa/osuwiki#1]
```scss
& .sum-time, & .req-time, & .parse-time {
  &:after {
    content: "ms";
  }
}
```
