### ISSUE TITLE
dark mode時の.dummy-navのbackground-colorを$darkcolorにする

### ISSUE THREAD

**Issue by Yukinyaaa** [Yukinyaaa/osuwiki#2]
```scss
& .dummy-nav {
  background-color: $darkcolor;
}
```
